export const JOB_LOCATIONS = [
	'Remote',
	'On-site',
	'Hybrid',
	'New York, USA',
	'San Francisco, USA',
	'Los Angeles, USA',
	'Chicago, USA',
	'Austin, USA',
	'Seattle, USA',
	'Boston, USA',
	'London, UK',
	'Manchester, UK',
	'Berlin, Germany',
	'Munich, Germany',
	'Amsterdam, Netherlands',
	'Paris, France',
	'Toronto, Canada',
	'Vancouver, Canada',
	'Sydney, Australia',
	'Melbourne, Australia',
	'Singapore',
	'Dubai, UAE',
	'Bangalore, India',
	'Mumbai, India',
] as const;

export const JOB_EMPLOYMENT_TYPES = [
	'Full-Time',
	'Part-Time',
	'Contract',
	'Freelance',
	'Internship',
] as const;

export const JOB_CATEGORIES = [
	'Engineering',
	'Design',
	'Marketing',
	'Sales',
	'Finance',
	'Operations',
	'Customer Support',
	'Human Resources',
	'Product',
	'Data & Analytics',
	'Legal',
	'Healthcare',
	'Education',
] as const;
