// AUTO‑GENERATED by update‑schema.mjs. Do not edit by hand.

import * as AuthSchema from "../models/drizzle/auth.model";
import * as EnumSchema from "../models/drizzle/enum.model";
import * as JobSchema from "../models/drizzle/job.model";
import * as RelationSchema from "../models/drizzle/relation.model";

const schema = {
	...AuthSchema,
	...EnumSchema,
	...JobSchema,
	...RelationSchema
};

export default schema;
